import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const WEBSITE_ROOT = path.resolve(__dirname, '..');
export const REPO_ROOT = path.resolve(WEBSITE_ROOT, '..');
export const GENERATED_DIR = path.join(WEBSITE_ROOT, 'src', 'generated');

export async function readRepoFile(relativePath) {
  return fs.readFile(path.join(REPO_ROOT, relativePath), 'utf8');
}

export async function ensureGeneratedDir() {
  await fs.mkdir(GENERATED_DIR, { recursive: true });
}

export async function writeGeneratedFile(filename, contents) {
  await ensureGeneratedDir();
  await fs.writeFile(path.join(GENERATED_DIR, filename), contents, 'utf8');
}

export function blockList(text, label) {
  const pattern = new RegExp(`${label}:\\n((?:\\s+- .+\\n)+)`, 'm');
  const match = text.match(pattern);
  if (!match) return [];

  return match[1]
    .split('\n')
    .map((line) => line.replace(/^\s*-\s+/, '').trim())
    .filter(Boolean);
}

export function sectionBetween(markdown, heading) {
  const pattern = new RegExp(`## ${heading}\\n([\\s\\S]*?)(?=\\n## |$)`, 'm');
  const match = markdown.match(pattern);
  return match ? match[1].trim() : '';
}

export function markdownBulletList(section) {
  return section
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.startsWith('- '))
    .map((line) => line.slice(2).trim());
}

export function toTsModule(constantName, value) {
  return `// This file is generated by website/scripts. Do not edit by hand.\nexport const ${constantName} = ${JSON.stringify(value, null, 2)} as const;\n`;
}
